services:
  jupyter:
    build: ./docker/jupyter/
    ## image: my-jupyter-windsurf

    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: start-notebook.sh --ServerApp.token='' --ServerApp.password=''

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
